version: '3.4'

services:
  dronemanagement:
    image: ${DOCKER_REGISTRY-}dronemanagement
    build:
      context: .
      dockerfile: DroneManagement/Dockerfile
    environment:
        DB_CONNECTION_STRING: "host=db;port:3000;username=postgres;password=postgres;database=dev"