version: '3.4'

services:
  dronemanagement:
    image: ${DOCKER_REGISTRY-}dronemanagement
    build:
      context: .
      dockerfile: DroneManagement/Dockerfile
    ports:
        - "3001:80"
        - "3000:443"